// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/affectations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/affectations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/affectations/index.post').default>>>>
    }
    '/api/affectations/remove': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/affectations/remove.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/manage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/manage.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/pending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/pending.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/simulate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/simulate.post').default>>>>
    }
    '/api/editions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/editions/[id].delete').default>>>>
    }
    '/api/editions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/editions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/editions/index.post').default>>>>
    }
    '/api/employes/:id/journal': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/employes/[id]/journal.get').default>>>>
    }
    '/api/equipe/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipe/[id].delete').default>>>>
    }
    '/api/equipe': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipe/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipe/index.post').default>>>>
    }
    '/api/journals/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id].put').default>>>>
    }
    '/api/journals/:id/entrees': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id]/entrees.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/[id]/entrees.post').default>>>>
    }
    '/api/journals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/journals/index.post').default>>>>
    }
    '/api/licences/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/licences/[id].delete').default>>>>
    }
    '/api/licences': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/licences/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/licences/index.post').default>>>>
    }
    '/api/meta/analyse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meta/analyse.post').default>>>>
    }
    '/api/meta/sync': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meta/sync.get').default>>>>
    }
    '/api/postes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/postes/index.get').default>>>>
    }
    '/api/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/index.get').default>>>>
    }
    '/api/seed-prod': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seed-prod.get').default>>>>
    }
    '/api/taches/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/[id].delete').default>>>>
    }
    '/api/taches/demandes/:id/decider': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/demandes/[id]/decider.post').default>>>>
    }
    '/api/taches/demandes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/demandes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/demandes/index.post').default>>>>
    }
    '/api/taches': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/index.post').default>>>>
    }
    '/api/taches/statuts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/taches/statuts.get').default>>>>
    }
    '/api/themes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/themes/[id].delete').default>>>>
    }
    '/api/themes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/themes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/themes/index.post').default>>>>
    }
    '/api/villes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/villes/[id].delete').default>>>>
    }
    '/api/villes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/villes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/villes/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}